### ISSUE TITLE
Создать шаблонные фразы для взаимодействия с пользователем

### ISSUE THREAD

**Issue by Perevalov** [Perevalov/polyclinica#56]
Разработать по 5-10 фраз на каждый из типов:
- Приветственные фразы (Добрый день, что у вас болит?)
- Уточняющие фразы (Правильно ли я понимаю, что вас беспокоит X?)
- Вопросительные фразы да/нет (Беспокоит ли вас следующий симптом: X?)
- Завершающие фразы (Я проанализировала ваши жалобы и выявила, что ...)

**Comment by Alexandrbatler** [comment]
Приветственные
Добрый день, что у вас болит?
Добрый день, что вас беспокоит?
Здраствуйте, напишите мне свои жалобы.
Приветствую вас, пожалуйтесь мне о своих болячках
Здраствуйте, можете рассказать мне о ваших недомоганиях
Добрый день, расскажите мне, пожалуйста, о вашей болезни
Здраствуйте, могу я услышать подробнее о вашем заболевании?
Доброго времени суток, сообщите мне о ваших проблемах со здоровьем

Уточняющие
Правильно ли я понимаю, что вас беспокоит X?
Уместно ли будет сказать, что вас беспокоит Х?
Целесообразно ли утверждение, что вас беспокоит х?
Верно ли утверждение, что вас беспокоит х?
Верно ли я понимаю, что вас беспокоит х?


Вопросительные фразы
Беспокоит ли вас следующий симптом: X?
Тревожит ли вас следующий симптом: Х?
Присутствует ли у вас такой симптом, как Х?
Докучает ли вам следующий симптом: Х?
Мучает ли вас следующий симптом: Х?



Завершающие фразы
Исходя из ваших жалоб я сделала вывод, что ...
Судя по вашим недомоганиям я выявила, что ...
Проанализировав ваши показания я могу сказать, что ...
Опираясь на ваши жалобы я сделала вывод, что ...
Основываясь на ваших жалобах, я выявила, что ...
