### ISSUE TITLE
Добавить кнопку "Регистрация" и логику работы с ней

### ISSUE THREAD

**Issue by Perevalov** [Perevalov/polyclinica#65]
1. На хедер добавить кнопку "регистрация".
2. При нажатии на эту кнопку должно возникать всплывающее окно с полем ввода email адреса и кнопкой "зарегистрироваться".
3. По нажатию кнопки "зарегистрироваться" всплывающее окно должно закрыться.
4. Логику верификации email и регистрации пока не вводим.

**Comment by alarionov93** [comment]
Кнопка перестала работать, это так надо, или нет?
