### ISSUE TITLE
Некорректная работа DialogueManager

### ISSUE THREAD

**Issue by Perevalov** [Perevalov/polyclinica#81]
Вводим первичный симптом, соглашаемся, затем, при опросе системой, несколько раз (или один) отвечаем нет, затем, говорим да и сразу же получаем диагноз. То есть после того, как сказали ДА, всегда заканчивается диалог.

**Comment by BobkovS** [comment]
Вроде все работает нормально, так что отложим на потом

**Comment by Perevalov** [comment]
Подтверждаю, что всё ок
