### ISSUE TITLE
Реализовать появление кнопки Записаться

### ISSUE THREAD

**Issue by Perevalov** [Perevalov/polyclinica#98]
Необходимо написать функцию на JS, которая скрывает кнопку "отправить" и текстовое поле в чате, и вместо них подставляет кнопку "Записаться". Cтиль кнопок брать аналогичный кнопке "отправить".
У функции должен быть некий булевский входной параметр, если он True, то мы скрываем кнопку отправить, а если False - то наоборот.

**Comment by alarionov93** [comment]
А где вся верстка вообще?

**Comment by Perevalov** [comment]
@alarionov93 В репозитории https://github.com/Perevalov/polyclinica_web

**Comment by alarionov93** [comment]
Событие и условие еще надо конкретизировать, когда такая кнопка должна появляться?

**Comment by alarionov93** [comment]
Пока сделал по hover на "Контакты"

**Comment by Perevalov** [comment]
@alarionov93 Такое событие сойдет, главное чтобы работало, потом переделаем

**Comment by alarionov93** [comment]
Окей

**Comment by alarionov93** [comment]
Добавь меня в polyclinica_web

**Comment by Perevalov** [comment]
@alarionov93 Смотри на почте инвайт

**Comment by Perevalov** [comment]
@alarionov93 Уже тестить можно? В след раз создавай отдельную ветку, а то у нас автодеплой на мастере настроен (polyclinica.org)

**Comment by alarionov93** [comment]
Окей, понял
